name: Publish Images

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
 
    strategy:
      fail-fast: false
      matrix:
        gover: [ 1.15 ]
        debver: [ buster, stretch ]
        include:
          - debver: stretch
            tag: 1.15-el7
          - debver: buster
            tag: 1.15

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
            
    - name: Build and push go ${{ matrix.tag }} based image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref_name == 'master' }}
        tags: tykio/golang-cross:${{ matrix.tag }}
        build-args: |
          GO_VERSION=${{ matrix.gover }}
          DEB_VERSION=${{ matrix.debver }}
